apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cicd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cicd-demo
  template:
    metadata:
      labels:
        app: flask-cicd-demo
    spec:
      containers:
      - name: flask-cicd-demo
        image: maayanamos/flask-cicd-demo:latest # The Docker image built and pushed via GitHub Actions
        ports:
        - containerPort: 5000
        # Liveness_probe- Checks if the container is still running properly
        # If this probe fails, Kubernetes will restart the container
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10  # Wait 10 seconds before first check
          periodSeconds: 10        # Check every 10 seconds
        # Readiness_probe- Checks if the app is ready to accept traffic
        # If this probe fails, the pod will not receive requests from the service  
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5  # Wait 5 seconds before first check
          periodSeconds: 5        # Check every 5 seconds
---
apiVersion: v1
kind: Service
metadata:
  name: flask-cicd-service
spec:
  type: NodePort
  selector:
    app: flask-cicd-demo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
